"""Fix backref conflict and add average rating

Revision ID: 2ecf99dcfa8c
Revises: 4d0262992810
Create Date: 2025-05-07 19:20:20.839904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecf99dcfa8c'
down_revision = '4d0262992810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
